name: Java CI

on:
  push:
    branches:
      - Head

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile Java
        run: javac Calculator.java

      - name: Run Java program
        run: java Calculator

      - name: Compile Java
        run: javac Calculator.java

      - name: Run Java program
        run: java Calculator